### ISSUE TITLE
[Review] Coding Conventions

### ISSUE THREAD

**Issue by hschovanec-usgs** [mhearne-usgs/shakemap-amp-tools#3]
**The following could cause test failures if Codacy or Travis CI are implemented later on:**

amptools/table.py

- Unused variables: EXCEL_DESC

amptools/io/cosmos/core.py

- Unused imports: timedelta, sys, os.path, UTCDateTime

amptools/io/knet/core.py

- Unused imports: timedelta, sys, os.path, UTCDateTime

bin/amps2xml

- Unused imports: sys, os.path, re, pandas, numpy

bin/sm2xml

- Unused imports: pandas, numpy

Missing spaces after commas will also cause a test failure.

**Other comments**

- Functions without docstrings: [_read_channel](https://github.com/mhearne-usgs/shakemap-amp-tools/blob/0eb5780e665039cb358e5a583b7a8b94d9692a9e/amptools/io/cosmos/core.py#L56), [_move](https://github.com/mhearne-usgs/shakemap-amp-tools/blob/c3f878ef0975759efa5c5045bfc0983ee50de3ca/amptools/table.py#L25), [_clean_sheet](https://github.com/mhearne-usgs/shakemap-amp-tools/blob/master/bin/sm2xml#L27), [_read_velocity](https://github.com/mhearne-usgs/shakemap-amp-tools/blob/0eb5780e665039cb358e5a583b7a8b94d9692a9e/amptools/io/geonet/core.py#L88)
- Global variables in most files are uppercase, while global variables in [table.py](https://github.com/mhearne-usgs/shakemap-amp-tools/blob/master/amptools/table.py) are lowercase.
- `__init__.py` file present tests/amptools/io/cosmos, but not in any other test subdirectories.

*Check coding standards based on code review [practices](https://github.com/usgs/best-practices/blob/0d134a060bb384789acb566d44c69762bf9df4c1/software/reviews.md#code-review).

**Comment by mhearne-usgs** [comment]
Unused variables/imports have been removed.
Missing spaces have been autopep8-ed out of existence.
Missing docstrings have been added (and _read_velocity removed, it was for debugging)
globals have been uppercased.

cosmos related issues will be left as an exercise for the reviewer :)
