### ISSUE TITLE
[Review] Documentation

### ISSUE THREAD

**Issue by hschovanec-usgs** [mhearne-usgs/shakemap-amp-tools#4]
The readme documentation is clear and makes sense. It might be helpful for users to see an example that shows how to use tools (sm2xml, ftpfetch, or amps2xml) with command line arguments. The introduction also lists tools included in the repository that convert data to XML format, but only lists amps2xml.

**Comment by mhearne-usgs** [comment]
README is now listing all command line utilities, except for smconvert which is a work in progress...
