### ISSUE TITLE
[Review] Privacy & Liscence

### ISSUE THREAD

**Issue by hschovanec-usgs** [mhearne-usgs/shakemap-amp-tools#5]
**Privacy**
There weren't any inclusions of PII, internal server host names, IP addresses, usernames, or passwords in the code. 

**Liscence**
- Is it okay to distribute the data included in tests/data?
- The link to the full legal code is missing.

**Comment by mhearne-usgs** [comment]
I modified the license file substantially (it was cut/pasted from the PAGER project, and had a lot of not relevant stuff in it).  The new license file now includes the link to the full legal code.

The strong motion records included in the tests are either freely available on-line, or provided to us by friendly cooperators, so I feel comfortable including them here.
